IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

DEPTH = ../../..
LDIRT = *.d
LCXXFLAGS = -I$(DEPTH)/include -DLIBRARYBUILD -DDEBUG

CXXFILES =\
	SoElement.c++ \
	SoElementInit.c++ \
	SoAccumulatedElement.c++ \
	SoReplacedElement.c++ \
	SoBBoxModelMatrixElement.c++ \
	SoCacheElement.c++ \
	SoClipPlaneElement.c++ \
	SoComplexityElement.c++ \
	SoComplexityTypeElement.c++ \
	SoCoordinateElement.c++ \
	SoCreaseAngleElement.c++ \
	SoDrawStyleElement.c++ \
	SoFloatElement.c++ \
	SoFocalDistanceElement.c++ \
	SoFontNameElement.c++ \
	SoFontSizeElement.c++ \
	SoGLCacheContextElement.c++ \
	SoGLClipPlaneElement.c++ \
	SoGLCoordinateElement.c++ \
	SoGLDrawStyleElement.c++ \
	SoGLLazyElement.c++ \
	SoGLLightIdElement.c++ \
	SoGLLinePatternElement.c++ \
	SoGLLineWidthElement.c++ \
	SoGLModelMatrixElement.c++ \
	SoGLNormalElement.c++ \
	SoGLPointSizeElement.c++ \
	SoGLProjectionMatrixElement.c++ \
	SoGLRenderPassElement.c++ \
	SoGLShapeHintsElement.c++ \
	SoGLTextureCoordinateElement.c++ \
	SoGLTextureEnabledElement.c++ \
	SoGLTextureImageElement.c++ \
	SoGLTextureMatrixElement.c++ \
	SoGLUpdateAreaElement.c++ \
	SoGLViewingMatrixElement.c++ \
	SoGLViewportRegionElement.c++ \
	SoLazyElement.c++ \
	SoLightAttenuationElement.c++ \
	SoLinePatternElement.c++ \
	SoLineWidthElement.c++ \
	SoLocalBBoxMatrixElement.c++ \
	SoInt32Element.c++ \
	SoMaterialBindingElement.c++ \
	SoModelMatrixElement.c++ \
	SoNormalBindingElement.c++ \
	SoNormalElement.c++ \
	SoOverrideElement.c++ \
	SoPickRayElement.c++ \
	SoPickStyleElement.c++ \
	SoPointSizeElement.c++ \
	SoProfileCoordinateElement.c++ \
	SoProfileElement.c++ \
	SoProjectionMatrixElement.c++ \
	SoShapeHintsElement.c++ \
	SoShapeStyleElement.c++ \
	SoSwitchElement.c++ \
	SoTextureCoordinateBindingElement.c++ \
	SoTextureCoordinateElement.c++ \
	SoTextureImageElement.c++ \
	SoTextureMatrixElement.c++ \
	SoTextureQualityElement.c++ \
	SoUnitsElement.c++ \
	SoViewVolumeElement.c++ \
	SoViewingMatrixElement.c++ \
	SoViewportRegionElement.c++ \
	SoWindowElement.c++ 

all:: $(OBJECTS)

include $(COMMONRULES)
