IVDEPTH = ../../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = misc/upgraders

HEADERS = \
	SoV1AppearanceKit.h SoV1BaseKit.h \
	SoV1CameraKit.h SoV1ConeKit.h \
	SoV1CubeKit.h SoV1CylinderKit.h \
	SoV1DirectionalLightKit.h SoV1FaceSetKit.h \
	SoV1GroupKit.h SoV1IndexedFaceSetKit.h \
	SoV1IndexedLineSetKit.h SoV1IndexedNurbsCurveKit.h \
	SoV1IndexedNurbsSurfaceKit.h SoV1IndexedTriangleMeshKit.h \
	SoV1LightKit.h SoV1LineSetKit.h \
	SoV1NodeKit.h SoV1NodekitCatalog.h \
	SoV1NodekitParts.h SoV1NurbsCurveKit.h \
	SoV1NurbsSurfaceKit.h SoV1OrthographicCameraKit.h \
	SoV1PerspectiveCameraKit.h SoV1PointLightKit.h \
	SoV1PointSetKit.h SoV1QuadMeshKit.h \
	SoV1SceneKit.h SoV1ShapeKit.h \
	SoV1SphereKit.h SoV1SpotLightKit.h \
	SoV1SubKit.h SoV1Text2Kit.h \
	SoV1Text3Kit.h SoV1TriangleStripSetKit.h \
	SoV1VertexShapeKit.h SoV1WrapperKit.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
