IVDEPTH = ../../../../../..
include $(IVDEPTH)/make/commonivdefs

DEPTH = ../../../..
LDIRT = *.d
LCXXFLAGS = -I$(DEPTH)/include -DLIBRARYBUILD  -DNDEBUG 

CXXFILES = triangulate.c++

all nurbs:: 
	@echo "XXX"

include $(COMMONRULES)
