IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/Xt/devices
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoXtDevice.h \
	SoXtInputFocus.h \
	SoXtKeyboard.h \
	SoXtMouse.h \
	SoXtSpaceball.h

LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

