IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

DEPTH = ../../..
LDIRT = *.d
LCXXFLAGS = -I$(DEPTH)/include -DLIBRARYBUILD -DDEBUG

CXXFILES =\
	SoField.c++ \
	SoFieldContainer.c++ \
	SoFieldData.c++ \
	SoFieldInit.c++ \
	SoGlobalField.c++ \
	SoMFBitMask.c++ \
	SoMFBool.c++ \
	SoMFColor.c++ \
	SoMFEngine.c++ \
	SoMFEnum.c++ \
	SoMFFloat.c++ \
	SoMFInt32.c++ \
	SoMFMatrix.c++ \
	SoMFName.c++ \
	SoMFNode.c++ \
	SoMFPath.c++ \
	SoMFPlane.c++ \
	SoMFRotation.c++ \
	SoMFShort.c++ \
	SoMFString.c++ \
	SoMFTime.c++ \
	SoMFUInt32.c++ \
	SoMFUShort.c++ \
	SoMFVec2f.c++ \
	SoMFVec3f.c++ \
	SoMFVec4f.c++ \
	SoSFBitMask.c++ \
	SoSFBool.c++ \
	SoSFColor.c++ \
	SoSFEngine.c++ \
	SoSFEnum.c++ \
	SoSFFloat.c++ \
	SoSFImage.c++ \
	SoSFInt32.c++ \
	SoSFMatrix.c++ \
	SoSFName.c++ \
	SoSFNode.c++ \
	SoSFPath.c++ \
	SoSFPlane.c++ \
	SoSFRotation.c++ \
	SoSFShort.c++ \
	SoSFString.c++ \
	SoSFTime.c++ \
	SoSFTrigger.c++ \
	SoSFUInt32.c++ \
	SoSFUShort.c++ \
	SoSFVec2f.c++ \
	SoSFVec3f.c++ \
	SoSFVec4f.c++

all:: $(OBJECTS)

include $(COMMONRULES)
