IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/projectors
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SbCylinderPlaneProjector.h \
	SbCylinderProjector.h \
	SbCylinderSectionProjector.h \
	SbCylinderSheetProjector.h \
	SbLineProjector.h \
	SbPlaneProjector.h \
	SbProjector.h \
	SbProjectors.h \
	SbSpherePlaneProjector.h \
	SbSphereProjector.h \
	SbSphereSectionProjector.h \
	SbSphereSheetProjector.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

