IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = projectors

HEADERS = \
	SbProjector.h \
	SbProjectors.h \
	SbCylinderPlaneProjector.h \
	SbCylinderProjector.h \
	SbCylinderSectionProjector.h \
	SbCylinderSheetProjector.h \
	SbLineProjector.h \
	SbPlaneProjector.h \
	SbSpherePlaneProjector.h \
	SbSphereProjector.h \
	SbSphereSectionProjector.h \
	SbSphereSheetProjector.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
