IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = jumpingJackKitTest

CXXFILES = JumpingJackKit.c++ jumpingJackKitTest.c++

LLDLIBS = -lInventor -lInventorXt

all: all_ivbin

include $(IVCOMMONRULES)
