IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = events

HEADERS = \
	SoButtonEvent.h \
	SoEvent.h \
	SoEvents.h \
	SoKeyboardEvent.h \
	SoLocation2Event.h \
	SoMotion3Event.h \
	SoMouseButtonEvent.h \
	SoSpaceballButtonEvent.h \
	SoSubEvent.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
