IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/events
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoButtonEvent.h \
	SoEvent.h \
	SoEvents.h \
	SoKeyboardEvent.h \
	SoLocation2Event.h \
	SoMotion3Event.h \
	SoMouseButtonEvent.h \
	SoSpaceballButtonEvent.h \
	SoSubEvent.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

