IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoBase.ivm \
	SoBaseList.ivm \
	SoByteStream.ivm \
	SoCallbackList.ivm \
	SoDB.ivm \
	SoInput.ivm \
	SoNodeKitPath.ivm \
	SoNodeList.ivm \
	SoOffscreenRenderer.ivm \
	SoOutput.ivm \
	SoPath.ivm \
	SoPathList.ivm \
	SoPickedPoint.ivm \
	SoPickedPointList.ivm \
	SoPrimitiveVertex.ivm \
	SoTranReceiver.ivm \
	SoTranSender.ivm \
	SoType.ivm \
	SoTypeList.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
