IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoCenterballManip.ivm \
	SoDirectionalLightManip.ivm \
	SoHandleBoxManip.ivm \
	SoJackManip.ivm \
	SoPointLightManip.ivm \
	SoSpotLightManip.ivm \
	SoTabBoxManip.ivm \
	SoTrackballManip.ivm \
	SoTransformBoxManip.ivm \
	SoTransformManip.ivm \
	SoTransformerManip.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
