IVDEPTH = ../../../..
include $(IVDEPTH)/make/commonivdefs

DEPTH = ..

SUBDIRS = \
	actions \
	basics \
	components \
	details \
	devices \
	draggers \
	engines \
	errors \
	events \
	fields \
	general \
	interaction \
	manips \
	nodekits \
	nodes \
	projectors \
	sensors \
	viewers

COMMONPREF = xxx
install $(COMMONTARGS) all:: 
	$(SUBDIRS_MAKERULE)

include $(COMMONRULES)
