IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SbCylinderPlaneProjector.ivm \
	SbCylinderProjector.ivm \
	SbCylinderSectionProjector.ivm \
	SbCylinderSheetProjector.ivm \
	SbLineProjector.ivm \
	SbPlaneProjector.ivm \
	SbProjector.ivm \
	SbSpherePlaneProjector.ivm \
	SbSphereProjector.ivm \
	SbSphereSectionProjector.ivm \
	SbSphereSheetProjector.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
