IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/details
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoConeDetail.h \
	SoCubeDetail.h \
	SoCylinderDetail.h \
	SoDetail.h \
	SoDetails.h \
	SoFaceDetail.h \
	SoLineDetail.h \
	SoPointDetail.h \
	SoSubDetail.h \
	SoTextDetail.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

