IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = details

HEADERS = \
	SoConeDetail.h \
	SoCubeDetail.h \
	SoCylinderDetail.h \
	SoDetail.h \
	SoDetails.h \
	SoFaceDetail.h \
	SoLineDetail.h \
	SoPointDetail.h \
	SoSubDetail.h \
	SoTextDetail.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
