IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

CXXFILES = \
	ConvertSFShortToSFFloat.c++ \
	FanIn.c++ MultFloatVec3f.c++ \
	SoComposeVec2f.c++ SoDecomposeVec2f.c++ \
	Ticker.c++

all: $(OBJECTS)

include $(IVCOMMONRULES)
