IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoAlarmSensor.ivm \
	SoDataSensor.ivm \
	SoDelayQueueSensor.ivm \
	SoFieldSensor.ivm \
	SoIdleSensor.ivm \
	SoNodeSensor.ivm \
	SoOneShotSensor.ivm \
	SoPathSensor.ivm \
	SoSensor.ivm \
	SoTimerQueueSensor.ivm \
	SoTimerSensor.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
