IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = componentTest

CXXFILES = componentTest.c++

LLDLIBS = libInventorWidget.a -lInventor -lInventorXt -lGL -lXm -lXt -lX11
ifneq ($(usingDarwin), 1)
LLDLIBS += -lGLw
endif

all install: all_ivbin

LTARGETS = libInventorWidget.a

libInventorWidget.a:
	cd `dirname $@`; make `basename $@`

include $(IVCOMMONRULES)
