IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = componentTest

CXXFILES = componentTest.c++

LLDLIBS = libInventorWidget.a -lInventor -lInventorXt -lGLw

LTARGETS = libInventorWidget.a

all install: all_ivbin

libInventorWidget.a:
	cd `dirname $@`; make `basename $@`

include $(IVCOMMONRULES)
