IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAMS_1 = spaceball spballViewer

CXXFILES = spaceball.c++ spballViewer.c++

LLDLIBS = -lInventor -lInventorXt

all: all_ivbin

include $(IVCOMMONRULES)
