IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = bundles

HEADERS = \
	SoBundle.h \
	SoMaterialBundle.h \
	SoNormalBundle.h \
	SoTextureCoordinateBundle.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
