IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAMS_1 = \
	02.1.HelloCone 02.2.EngineSpin \
	02.3.Trackball 02.4.Examiner \
	03.1.Molecule 03.2.Robot 03.3.Naming \
	04.1.Cameras 04.2.Lights \
	05.1.FaceSet 05.2.IndexedFaceSet \
	05.3.TriangleStripSet 05.4.QuadMesh \
	05.5.Binding 05.6.TransformOrdering \
	06.1.Text 06.2.Simple3DText 06.3.Complex3DText \
	07.1.BasicTexture 07.2.TextureCoordinates \
	07.3.TextureFunction \
	08.1.BSCurve 08.2.UniCurve 08.3.BezSurf \
	08.4.TrimSurf \
	09.1.Print  09.2.Texture 09.3.Search \
	09.4.PickAction 09.5.GenSph \
	10.1.addEventCB 10.2.setEventCB \
	10.3and4.MotifList 10.5.SelectionCB \
        10.6.PickFilterTopLevel 10.7.PickFilterManip \
	10.8.PickFilterNodeKit \
	11.1.ReadFile 11.2.ReadString \
	12.1.FieldSensor 12.2.NodeSensor \
	12.3.AlarmSensor 12.4.TimerSensor \
	13.1.GlobalFlds \
	13.2.ElapsedTime 13.3.TimeCounter \
	13.4.Gate 13.5.Boolean 13.6.Calculator \
	13.7.Rotor 13.8.Blinker \
	14.1.FrolickingWords 14.2.Editors 14.3.Balance \
	15.1.ConeRadius 15.2.SliderBox 15.3.AttachManip \
	15.4.Customize \
	16.1.Overlay 16.2.Callback 16.3.AttachEditor \
	16.4.OneWindow 16.5.Examiner \
	17.1.ColorIndex 17.2.GLCallback 17.3.GLFloor

LLDLIBS = -lInventor -lInventorXt

all: all_ivbin

include $(IVCOMMONRULES)
