IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoXt.ivm \
	SoXtClipboard.ivm \
	SoXtComponent.ivm \
	SoXtDirectionalLightEditor.ivm \
	SoXtGLWidget.ivm \
	SoXtLightSliderSet.ivm \
	SoXtMaterialEditor.ivm \
	SoXtMaterialList.ivm \
	SoXtMaterialSliderSet.ivm \
	SoXtPrintDialog.ivm \
	SoXtRenderArea.ivm \
	SoXtResource.ivm \
	SoXtSliderSet.ivm \
	SoXtSliderSetBase.ivm \
	SoXtTransformSliderSet.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
