IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoConeDetail.ivm \
	SoCubeDetail.ivm \
	SoCylinderDetail.ivm \
	SoDetail.ivm \
	SoDetailList.ivm \
	SoFaceDetail.ivm \
	SoLineDetail.ivm \
	SoNodeKitDetail.ivm \
	SoPointDetail.ivm \
	SoTextDetail.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
