IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoXtDevice.ivm \
	SoXtInputFocus.ivm \
	SoXtKeyboard.ivm \
	SoXtMouse.ivm \
	SoXtSpaceball.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
