IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

CXXFILES = \
	SoXtCntlPnl.c++ \
	SoXtFltTxt.c++ \
	SoXtLtSldrSet.c++ \
	SoXtMMSldrMax.c++ \
	SoXtMMSldrMin.c++ \
	SoXtMinMax.c++ \
	SoXtMltSldr.c++ \
	SoXtMltSldrs.c++ \
	SoXtMtlSSet.c++ \
	SoXtSSetBase.c++ \
	SoXtSldrMdl.c++ \
	SoXtSldrMdls.c++ \
	SoXtSldrSet.c++ \
	SoXtSldrTl.c++ \
	SoXtTfSldrSet.c++

all install: $(OBJECTS) 

include $(IVCOMMONRULES)
