IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/fields
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoField.h \
	SoFieldContainer.h \
	SoFieldData.h \
	SoFields.h \
	SoMFBitMask.h \
	SoMFBool.h \
	SoMFColor.h \
	SoMFEngine.h \
	SoMFEnum.h \
	SoMFFloat.h \
	SoMFInt32.h \
	SoMFLong.h \
	SoMFMatrix.h \
	SoMFName.h \
	SoMFNode.h \
	SoMFPath.h \
	SoMFPlane.h \
	SoMFRotation.h \
	SoMFShort.h \
	SoMFString.h \
	SoMFTime.h \
	SoMFUInt32.h \
	SoMFULong.h \
	SoMFUShort.h \
	SoMFVec2f.h \
	SoMFVec3f.h \
	SoMFVec4f.h \
	SoSFBitMask.h \
	SoSFBool.h \
	SoSFColor.h \
	SoSFEngine.h \
	SoSFEnum.h \
	SoSFFloat.h \
	SoSFImage.h \
	SoSFInt32.h \
	SoSFLong.h \
	SoSFMatrix.h \
	SoSFName.h \
	SoSFNode.h \
	SoSFPath.h \
	SoSFPlane.h \
	SoSFRotation.h \
	SoSFShort.h \
	SoSFString.h \
	SoSFTime.h \
	SoSFTrigger.h \
	SoSFUInt32.h \
	SoSFULong.h \
	SoSFUShort.h \
	SoSFVec2f.h \
	SoSFVec3f.h \
	SoSFVec4f.h \
	SoSubField.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

