IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivnorm

CXXFILES = \
	ivnorm.c++ FindNormals.c++ \
	Faces.c++ Edges.c++

LLDLIBS = -lInventor

all: all_ivbin

install: install_ivbin

include $(IVCOMMONRULES)
