IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

DSO = Decal.so

CXXFILES = Decal.c++

LLDLIBS = -lGL -L$(IVDEPTH)/lib -lInventor -L$(IVDEPTH)/libSoXt -lInventorXt

all install: all_ivbin

include $(IVCOMMONRULES)
