IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoAppearanceKit.ivm \
	SoBaseKit.ivm \
	SoCameraKit.ivm \
	SoInteractionKit.ivm \
	SoLightKit.ivm \
	SoNodeKit.ivm \
	SoNodeKitListPart.ivm \
	SoNodekitCatalog.ivm \
	SoSceneKit.ivm \
	SoSeparatorKit.ivm \
	SoShapeKit.ivm \
	SoWrapperKit.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
