IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = manips

HEADERS = \
	SoCenterballManip.h SoDirectionalLightManip.h \
	SoHandleBoxManip.h SoJackManip.h \
	SoPointLightManip.h SoSpotLightManip.h \
	SoTabBoxManip.h SoTrackballManip.h \
	SoTransformBoxManip.h SoTransformerManip.h \
	SoTransformManip.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
