IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/manips
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoCenterballManip.h \
	SoDirectionalLightManip.h \
	SoHandleBoxManip.h \
	SoJackManip.h \
	SoPointLightManip.h \
	SoSpotLightManip.h \
	SoTabBoxManip.h \
	SoTrackballManip.h \
	SoTransformBoxManip.h \
	SoTransformManip.h \
	SoTransformerManip.h

LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

