IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = overlayTest

CXXFILES = overlayTest.c++ OverlayHL.c++

LLDLIBS = -lInventor -lInventorXt

all: all_ivbin

include $(IVCOMMONRULES)
