IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SbBool.ivm \
        SbBox2f.ivm \
        SbBox2s.ivm \
        SbBox3f.ivm \
        SbColor.ivm \
        SbCylinder.ivm \
        SbLine.ivm \
        SbMatrix.ivm \
        SbName.ivm \
        SbPList.ivm \
        SbPlane.ivm \
        SbRotation.ivm \
        SbSphere.ivm \
        SbString.ivm \
        SbTime.ivm \
        SbVec2f.ivm \
        SbVec2s.ivm \
        SbVec3f.ivm \
        SbVec4f.ivm \
        SbViewVolume.ivm \
        SbViewportRegion.ivm \
        SbXfBox3f.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
