IVDEPTH = ..
include $(IVDEPTH)/make/ivcommondefs

ARCHIVE = libimage.a

CFILES = \
	close.c \
	filbuf.c \
	flsbuf.c \
	name.c \
	open.c \
	pix.c \
	rdwr.c \
	rle.c \
	row.c

all install: all_ivbin

include $(IVCOMMONRULES)
