IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = errors

HEADERS = \
	SoDebugError.h \
	SoError.h \
	SoErrors.h \
	SoMemoryError.h \
	SoReadError.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
