IVDEPTH = ../../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = misc/upgraders

HEADERS = \
	SoUpgrader.h \
	SoV1CustomNode.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
