IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoCenterballDragger.ivm \
	SoDirectionalLightDragger.ivm \
	SoDragPointDragger.ivm \
	SoDragger.ivm \
	SoHandleBoxDragger.ivm \
	SoJackDragger.ivm \
	SoPointLightDragger.ivm \
	SoRotateCylindricalDragger.ivm \
	SoRotateDiscDragger.ivm \
	SoRotateSphericalDragger.ivm \
	SoScale1Dragger.ivm \
	SoScale2Dragger.ivm \
	SoScale2UniformDragger.ivm \
	SoScaleUniformDragger.ivm \
	SoSpotLightDragger.ivm \
	SoTabBoxDragger.ivm \
	SoTabPlaneDragger.ivm \
	SoTrackballDragger.ivm \
	SoTransformBoxDragger.ivm \
	SoTransformerDragger.ivm \
	SoTranslate1Dragger.ivm \
	SoTranslate2Dragger.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
