IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/actions
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoBoxHighlightRenderAction.h \
	SoLineHighlightRenderAction.h

LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

