IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = nodes

HEADERS = \
	SoAnnotation.h \
	SoArray.h \
	SoAsciiText.h \
	SoBaseColor.h \
	SoBlinker.h \
	SoCallback.h \
	SoCamera.h \
	SoClipPlane.h \
	SoColorIndex.h \
	SoComplexity.h \
	SoCone.h \
	SoCoordinate3.h \
	SoCoordinate4.h \
	SoCube.h \
	SoCylinder.h \
	SoDirectionalLight.h \
	SoDrawStyle.h \
	SoEnvironment.h \
	SoEventCallback.h \
	SoFaceSet.h \
	SoFile.h \
	SoFont.h \
	SoFontStyle.h \
	SoGroup.h \
	SoIndexedFaceSet.h \
	SoIndexedLineSet.h \
	SoIndexedNurbsCurve.h \
	SoIndexedNurbsSurface.h \
	SoIndexedShape.h \
	SoIndexedTriangleStripSet.h \
	SoInfo.h \
	SoLabel.h \
	SoLevelOfDetail.h \
	SoLOD.h \
	SoLocateHighlight.h \
	SoLight.h \
	SoLightModel.h \
	SoLineSet.h \
	SoLinearProfile.h \
	SoMaterial.h \
	SoMaterialBinding.h \
	SoMatrixTransform.h \
	SoMultipleCopy.h \
	SoNode.h \
	SoNodes.h \
	SoNonIndexedShape.h \
	SoNormal.h \
	SoNormalBinding.h \
	SoNurbsCurve.h \
	SoNurbsProfile.h \
	SoNurbsSurface.h \
	SoOrthographicCamera.h \
	SoPackedColor.h \
	SoPathSwitch.h \
	SoPendulum.h \
	SoPerspectiveCamera.h \
	SoPickStyle.h \
	SoPointLight.h \
	SoPointSet.h \
	SoProfile.h \
	SoProfileCoordinate2.h \
	SoProfileCoordinate3.h \
	SoQuadMesh.h \
	SoResetTransform.h \
	SoRotation.h \
	SoRotationXYZ.h \
	SoRotor.h \
	SoScale.h \
	SoSeparator.h \
	SoShape.h \
	SoShapeHints.h \
	SoShuttle.h \
	SoSphere.h \
	SoSpotLight.h \
	SoSubNode.h \
	SoSwitch.h \
	SoText2.h \
	SoText3.h \
	SoTexture2.h \
	SoTexture2Transform.h \
	SoTextureCoordinate2.h \
	SoTextureCoordinateBinding.h \
	SoTextureCoordinateDefault.h \
	SoTextureCoordinateEnvironment.h \
	SoTextureCoordinateFunction.h \
	SoTextureCoordinatePlane.h \
	SoTransform.h \
	SoTransformSeparator.h \
	SoTransformation.h \
	SoTranslation.h \
	SoTriangleStripSet.h \
	SoUnits.h \
	SoVertexProperty.h\
	SoVertexShape.h \
	SoWWWAnchor.h \
	SoWWWInline.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
