IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = engines

HEADERS = \
	SoBoolOperation.h \
	SoCalculator.h \
	SoCompose.h \
	SoComputeBoundingBox.h \
	SoConcatenate.h \
	SoCounter.h \
	SoElapsedTime.h \
	SoEngine.h \
	SoEngines.h \
	SoFieldConverter.h \
	SoGate.h \
	SoInterpolate.h \
	SoOnOff.h \
	SoOneShot.h \
	SoOutputData.h \
	SoSelectOne.h \
	SoSubEngine.h \
	SoTimeCounter.h \
	SoTransformVec3f.h \
	SoTriggerAny.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
