IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/engines
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoBoolOperation.h \
	SoCalculator.h \
	SoCompose.h \
	SoComputeBoundingBox.h \
	SoConcatenate.h \
	SoCounter.h \
	SoElapsedTime.h \
	SoEngine.h \
	SoEngines.h \
	SoFieldConverter.h \
	SoGate.h \
	SoInterpolate.h \
	SoOnOff.h \
	SoOneShot.h \
	SoOutputData.h \
	SoSelectOne.h \
	SoSubEngine.h \
	SoTimeCounter.h \
	SoTransformVec3f.h \
	SoTriggerAny.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

