IVDEPTH = ../../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = newNodes

CXXFILES = newNodes.c++ Glow.c++ Pyramid.c++ Alternate.c++

LLDLIBS = -lInventor -lInventorXt

all: all_ivbin

include $(IVCOMMONRULES)
