IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoButtonEvent.ivm \
	SoEvent.ivm \
	SoKeyboardEvent.ivm \
	SoLocation2Event.ivm \
	SoMotion3Event.ivm \
	SoMouseButtonEvent.ivm \
	SoSpaceballButtonEvent.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
