IVDEPTH = ../..
include $(IVDEPTH)/make/commonivdefs

SUBDIRS = \
	SceneViewer \
	drop \
	gview \
	maze \
	noodle \
	qmorf \
	revo \
	textomatic

COMMONPREF = xxx
all $(COMMONTARGS) install:
	$(SUBDIRS_MAKERULE)

include $(COMMONRULES)
