IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoAction.ivm \
	SoCallbackAction.ivm \
	SoGLRenderAction.ivm \
	SoGetBoundingBoxAction.ivm \
	SoGetMatrixAction.ivm \
	SoHandleEventAction.ivm \
	SoPickAction.ivm \
	SoRayPickAction.ivm \
	SoSearchAction.ivm \
	SoWriteAction.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
