IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoBoxHighlightRenderAction.ivm \
	SoEventCallback.ivm \
	SoInteraction.ivm \
	SoLineHighlightRenderAction.ivm \
	SoSceneManager.ivm \
	SoSelection.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
