IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = draggers

HEADERS = \
	SoCenterballDragger.h SoDirectionalLightDragger.h \
	SoDragPointDragger.h SoDragger.h \
	SoHandleBoxDragger.h SoJackDragger.h \
	SoPointLightDragger.h SoRotateCylindricalDragger.h \
	SoRotateDiscDragger.h SoRotateSphericalDragger.h \
	SoScale1Dragger.h SoScale2Dragger.h \
	SoScale2UniformDragger.h SoScaleUniformDragger.h \
	SoSpotLightDragger.h SoTabBoxDragger.h \
	SoTabPlaneDragger.h SoTrackballDragger.h \
	SoTransformBoxDragger.h SoTransformerDragger.h \
	SoTranslate1Dragger.h SoTranslate2Dragger.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
