IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/draggers
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoCenterballDragger.h \
	SoDirectionalLightDragger.h \
	SoDragPointDragger.h \
	SoDragger.h \
	SoHandleBoxDragger.h \
	SoJackDragger.h \
	SoPointLightDragger.h \
	SoRotateCylindricalDragger.h \
	SoRotateDiscDragger.h \
	SoRotateSphericalDragger.h \
	SoScale1Dragger.h \
	SoScale2Dragger.h \
	SoScale2UniformDragger.h \
	SoScaleUniformDragger.h \
	SoSpotLightDragger.h \
	SoTabBoxDragger.h \
	SoTabPlaneDragger.h \
	SoTrackballDragger.h \
	SoTransformBoxDragger.h \
	SoTransformerDragger.h \
	SoTranslate1Dragger.h \
	SoTranslate2Dragger.h \

LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

