IVDEPTH = ../..
include $(IVDEPTH)/make/commonivdefs

SUBDIRS = \
	ivcat \
	ivfix \
	ivinfo \
	ivquicken \
	ivview

COMMONPREF = xxx
$(COMMONTARGS) all install:
	$(SUBDIRS_MAKERULE)

include $(COMMONRULES)
