IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/Xt/viewers
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoXtConstrainedViewer.h \
	SoXtExaminerViewer.h \
	SoXtFlyViewer.h \
	SoXtFullViewer.h \
	SoXtPlaneViewer.h \
	SoXtViewer.h \
	SoXtWalkViewer.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

