IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = Xt/viewers

HEADERS = \
	SoXtConstrainedViewer.h \
	SoXtExaminerViewer.h \
	SoXtFlyViewer.h \
	SoXtFullViewer.h \
	SoXtPlaneViewer.h \
	SoXtViewer.h \
	SoXtWalkViewer.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
