IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/nodekits
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoAppearanceKit.h \
	SoBaseKit.h \
	SoCameraKit.h \
	SoLightKit.h \
	SoNodeKit.h \
	SoNodeKitListPart.h \
	SoNodekitCatalog.h \
	SoNodekitParts.h \
	SoSceneKit.h \
	SoSeparatorKit.h \
	SoShapeKit.h \
	SoSubKit.h \
	SoWrapperKit.h

LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

