IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = nodekits

HEADERS = \
	SoAppearanceKit.h SoBaseKit.h \
	SoCameraKit.h SoLightKit.h \
	SoNodeKit.h SoNodeKitListPart.h \
	SoNodekitCatalog.h SoNodekitParts.h \
	SoSceneKit.h SoSeparatorKit.h \
	SoShapeKit.h SoSubKit.h \
	SoWrapperKit.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
