IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = actions

HEADERS = \
	SoAction.h \
	SoActions.h \
	SoCallbackAction.h \
	SoGLRenderAction.h \
	SoGetBoundingBoxAction.h \
	SoGetMatrixAction.h \
	SoHandleEventAction.h \
	SoPickAction.h \
	SoRayPickAction.h \
	SoSearchAction.h \
	SoSubAction.h \
	SoWriteAction.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
