IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/actions
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoAction.h \
	SoActions.h \
	SoCallbackAction.h \
	SoGLRenderAction.h \
	SoGetBoundingBoxAction.h \
	SoGetMatrixAction.h \
	SoHandleEventAction.h \
	SoPickAction.h \
	SoRayPickAction.h \
	SoSearchAction.h \
	SoSubAction.h \
	SoWriteAction.h


LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

