'\"macro stdmacro
.TH drop 1
.SH NAME
drop \- a 3d skill game
.SH SYNOPSIS
.B drop
.SH DESCRIPTION
.I drop
is a fun game that tests your ability to drop 3d puzzle pieces onto a grid.
The goal of the game is to drop the puzzle pieces onto the green court
and form a solid grid of cubes.  Each time that you fill an entire
grid, that grid unit will glow brightly and drop down and off the court.
You get extra points for each complete grid unit that you fill.  If you get
enough points during a game, then you move to the next (more difficult)
level. The game will get progressively harder as you ascend the levels (1-5).
.PP
Type
.I drop
, and then immediately press the 'h' key for detailed playing instructions.
.PP
This game was written using the Inventor 3d Toolkit.
.SH SOURCE CODE
Note that the source code to 
.I drop 
comes with the
.I Open Inventor 3d Toolkit.
.SH FILES
/usr/share/src/Inventor/demos/drop/* - Source to drop
.SH SEE ALSO
.TP
maze, inventor, noodle, qmorf, revo, textomatic
