IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

MAN1PAGES = \
	SceneViewer.1 \
	inventor.1 \
	iv2toiv1.1 \
	ivcat.1 \
	ivdowngrade.1 \
	ivfix.1 \
	ivinfo.1 \
	ivview.1

all install: install_man1

include $(IVCOMMONRULES)
