IVDEPTH = ../../../../..
include $(IVDEPTH)/make/commonivdefs

INST_HEADER_ROOT   = $(IVROOT)/usr/include/Inventor/nodekits
HEADER_PATH        = $(INST_HEADER_ROOT)
NOSHIP_HEADER_PATH = $(HEADER_PATH)

INST_HEADERS = \
	SoInteractionKit.h 

LDIRT = $(INST_HEADER_ROOT)

install: headers

include $(IVCOMMONRULES)

