IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoXtConstrainedViewer.ivm \
	SoXtExaminerViewer.ivm \
	SoXtFlyViewer.ivm \
	SoXtFullViewer.ivm \
	SoXtPlaneViewer.ivm \
	SoXtViewer.ivm \
	SoXtWalkViewer.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
