IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = sensors

HEADERS = \
	SoAlarmSensor.h \
	SoDataSensor.h \
	SoDelayQueueSensor.h \
	SoFieldSensor.h \
	SoIdleSensor.h \
	SoNodeSensor.h \
	SoOneShotSensor.h \
	SoPathSensor.h \
	SoSensor.h \
	SoSensorManager.h \
	SoSensors.h \
	SoTimerQueueSensor.h \
	SoTimerSensor.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
