IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivview

CXXFILES = ivview.c++

LLDOPTS += -L../../samples/widgets

LLDLIBS = -lInventorWidget -lInventorXt -lInventor

all: all_ivbin

install: install_ivbin

include $(IVCOMMONRULES)
