IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

IVMFILES = \
	SoDebugError.ivm \
	SoError.ivm \
	SoMemoryError.ivm \
	SoReadError.ivm

all: all_man3iv

install: install_man3iv

include $(IVCOMMONRULES)
