IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

PROGRAM = ivfix

CXXFILES = \
	ivfix.c++ 	\
	IfBuilder.c++	\
	IfCollector.c++	\
	IfCondenser.c++	\
	IfFixer.c++	\
	IfFlattener.c++	\
	IfHasher.c++	\
	IfHolder.c++	\
	IfMerger.c++	\
	IfReplacer.c++	\
	IfReporter.c++	\
	IfShape.c++	\
	IfShapeList.c++	\
	IfSorter.c++	\
	IfStripper.c++	\
	IfTypes.c++	\
	IfWeeder.c++

LLDLIBS = -lInventor

all: all_ivbin

install: install_ivbin

include $(IVCOMMONRULES)
