IVDEPTH = ../../../../..
include $(IVDEPTH)/make/ivcommondefs

HDRSUBDIR = elements

HEADERS = \
	SoAccumulatedElement.h \
	SoAmbientColorElement.h \
	SoBBoxModelMatrixElement.h \
	SoCacheElement.h \
	SoClipPlaneElement.h \
	SoComplexityElement.h \
	SoComplexityTypeElement.h \
	SoCoordinateElement.h \
	SoCreaseAngleElement.h \
	SoDrawStyleElement.h \
	SoElement.h \
	SoElements.h \
	SoEmissiveColorElement.h \
	SoFloatElement.h \
	SoFocalDistanceElement.h \
	SoFontNameElement.h \
	SoFontSizeElement.h \
	SoGLCacheContextElement.h \
	SoGLClipPlaneElement.h \
	SoGLColorIndexElement.h \
	SoGLCoordinateElement.h \
	SoGLDrawStyleElement.h \
	SoGLLazyElement.h \
	SoGLLightIdElement.h \
	SoGLLinePatternElement.h \
	SoGLLineWidthElement.h \
	SoGLModelMatrixElement.h \
	SoGLNormalElement.h \
	SoGLPointSizeElement.h \
	SoGLProjectionMatrixElement.h \
	SoGLRenderPassElement.h \
	SoGLShapeHintsElement.h \
	SoGLTextureCoordinateElement.h \
	SoGLTextureEnabledElement.h \
	SoGLTextureImageElement.h \
	SoGLTextureMatrixElement.h \
	SoGLUpdateAreaElement.h \
	SoGLViewingMatrixElement.h \
	SoGLViewportRegionElement.h \
	SoLazyElement.h \
	SoLightAttenuationElement.h \
	SoLightModelElement.h \
	SoLinePatternElement.h \
	SoLineWidthElement.h \
	SoLocalBBoxMatrixElement.h \
	SoLongElement.h \
	SoInt32Element.h \
	SoMaterialBindingElement.h \
	SoModelMatrixElement.h \
	SoNormalBindingElement.h \
	SoNormalElement.h \
	SoOverrideElement.h \
	SoPickRayElement.h \
	SoPickStyleElement.h \
	SoPointSizeElement.h \
	SoProfileCoordinateElement.h \
	SoProfileElement.h \
	SoProjectionMatrixElement.h \
	SoReplacedElement.h \
	SoShapeHintsElement.h \
	SoShapeStyleElement.h \
	SoShininessElement.h \
	SoSpecularColorElement.h \
	SoSubElement.h \
	SoSwitchElement.h \
	SoTextureCoordinateBindingElement.h \
	SoTextureCoordinateElement.h \
	SoTextureImageElement.h \
	SoTextureMatrixElement.h \
	SoTextureQualityElement.h \
	SoUnitsElement.h \
	SoViewVolumeElement.h \
	SoViewingMatrixElement.h \
	SoViewportRegionElement.h \
	SoWindowElement.h \
	SoCullVolumeElement.h \
	SoCurrentGLMaterialElement.h \
	SoDiffuseColorElement.h \
	SoGLAmbientColorElement.h \
	SoGLDiffuseColorElement.h \
	SoGLEmissiveColorElement.h \
	SoGLLightModelElement.h \
	SoGLPolygonStippleElement.h \
	SoGLShininessElement.h \
	SoGLSpecularColorElement.h \
	SoGLTextureBlendColorElement.h \
	SoGLTextureModelElement.h \
	SoGLTextureQualityElement.h \
	SoGLTextureWrapSElement.h \
	SoGLTextureWrapTElement.h \
	SoTextureBlendColorElement.h \
	SoTextureModelElement.h \
	SoTextureWrapSElement.h \
	SoTextureWrapTElement.h \
	SoTransparencyElement.h

all:

install: install_ivheaders

include $(IVCOMMONRULES)
