IVDEPTH = ../../..
include $(IVDEPTH)/make/ivcommondefs

DSO = BarChart.so

CXXFILES = BarChart.c++

LLDLIBS = -L$(IVDEPTH)/lib -lInventor -L$(IVDEPTH)/libSoXt -lInventorXt

all install: all_ivbin

include $(IVCOMMONRULES)
